[package]
name = 'prj01'
version = '0.1.0'
authors = ['Antonio Feitosa <antonio.cfc@gmail.com>']
edition = '2018'

[dependencies]
# async-h1 = "2.1.0"
# http-types = "2.2.1"


[dependencies.async-std]
version = '1.6.2'
features = ['attributes']
